# Generated by Django 4.1.3 on 2023-05-18 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hole.utils.default_values


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(max_length=1000, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('joined_time', models.DateTimeField(auto_now_add=True)),
                ('nickname', models.CharField(blank=True, max_length=32, unique=True)),
                ('permission', models.JSONField(default=hole.utils.default_values.default_permission)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='ActiveUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=hole.utils.default_values.default_active_user_date, unique=True)),
                ('dau', models.IntegerField(default=0)),
                ('mau', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'active_user',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div', models.CharField(default='校园生活', max_length=32, unique=True)),
                ('sec', models.CharField(default='日常', max_length=32, unique=True)),
                ('description', models.TextField(null=True)),
                ('pinned', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'division',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('shadow_text', models.TextField(default='')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('like', models.IntegerField(db_index=True, default=0)),
                ('like_data', models.JSONField(default=list)),
                ('deleted', models.BooleanField(default=False)),
                ('history', models.JSONField(default=list)),
                ('storey', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'floor',
            },
        ),
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('view', models.IntegerField(db_index=True, default=0, help_text='浏览量')),
                ('reply', models.IntegerField(db_index=True, default=-1, help_text='楼层数')),
                ('division', models.ForeignKey(help_text='分区', on_delete=django.db.models.deletion.CASCADE, to='hole.division')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hole',
            },
        ),
        migrations.CreateModel(
            name='OldUserFavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=11)),
                ('favorites', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('dealed', models.BooleanField(db_index=True, default=False)),
                ('dealed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hole.floor')),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hole.hole')),
            ],
            options={
                'db_table': 'report',
            },
        ),
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(db_index=True, max_length=16)),
                ('device_id', models.CharField(max_length=128, unique=True)),
                ('token', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'push_token',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='')),
                ('code', models.CharField(default='', max_length=30)),
                ('data', models.JSONField(default=dict)),
                ('has_read', models.BooleanField(default=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.AddField(
            model_name='floor',
            name='hole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hole.hole'),
        ),
        migrations.AddField(
            model_name='floor',
            name='mention',
            field=models.ManyToManyField(blank=True, related_name='mentioned_by', to='hole.floor'),
        ),
        migrations.AddField(
            model_name='floor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favored_by', to='hole.hole'),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
