# Generated by Django 4.1.3 on 2023-05-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hole', '0003_alter_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hole',
            name='time_updated',
        ),
        migrations.RemoveField(
            model_name='hole',
            name='view',
        ),
        migrations.AddField(
            model_name='hole',
            name='content',
            field=models.TextField(help_text='帖子内容', null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='hole',
            name='favourites',
            field=models.JSONField(default=list, help_text='收藏列表'),
        ),
        migrations.AddField(
            model_name='hole',
            name='likes',
            field=models.JSONField(default=list, help_text='点赞列表'),
        ),
        migrations.AlterField(
            model_name='hole',
            name='reply',
            field=models.IntegerField(db_index=True, default=0, help_text='楼层数'),
        ),
        migrations.AlterField(
            model_name='hole',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
