# Generated by Django 4.1.3 on 2023-05-21 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hole', '0005_alter_hole_division'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floor',
            old_name='history',
            new_name='likes',
        ),
        migrations.RemoveField(
            model_name='floor',
            name='like',
        ),
        migrations.RemoveField(
            model_name='floor',
            name='like_data',
        ),
    ]
